version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:20
    steps:
      - checkout
      
      - run:
          name: Install dependencies
          command: npm ci
      
      - run:
          name: Release
          command: npx semantic-release
          environment:
            NPM_TOKEN: ${NPM_TOKEN}
            GITHUB_TOKEN: ${GITHUB_TOKEN}

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              only: main
