name: Auto Tag

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write  # Explicitly grant write permissions to contents

jobs:
  auto-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Commitizen
        run: npm install -g commitizen

      - name: Generate Tag
        id: tag
        run: |
          # Fetch all tags
          git fetch --tags

          # List all tags for debugging purposes
          echo "Listing all tags:"
          git tag -l
          
          # Get the latest tag
          latestTag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag: $latestTag"

          # Generate the new tag based on the latest tag
          if [[ $latestTag == "" ]]; then
            newTag="v1.0.0"
          else
            newTag=$(npm version patch)
          fi
          echo "New tag: $newTag"

          # Set output
          echo "::set-output name=new_tag::$newTag"

      - name: Create Git Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name 'HiKanav'
          git config --global user.email 'say@hikanav.com'
          git tag ${{ steps.tag.outputs.new_tag }}
          git push origin ${{ steps.tag.outputs.new_tag }}
